### ISSUE TITLE
Change 'play' and 'games' to 'games' and 'store'

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#134]
It's a bit easier when you're on automatic to have it that way. Anybody agree?

**Comment by ssokolow** [comment]
I find it about equal, actually. I think habit plays a large part in that. However, I will agree that Games/Store is probably more intuitive for new users than Play/Games.

(It's also more consistent, since "Play" is a verb, but "Games", "Community", "Development", and "Support" are nouns describing classes of things)

**Comment by hero1900** [comment]
i think this is a good idea it make more sense

**Comment by mathrick** [comment]
+1 to this. I found the "Play" wording extremely confusing and it actually took me good 15 minutes to find a way to play my first purchased game. There's another related design issue lurking here: <myaccountname> and Play are not separated visually enough, and this causes the word "Play" to disappear from the view, at least for me, because I look at it as a part of my profile icon. There should be a clear, unmistakable separator in the default skin. I suggest making the word Games (formerly Play) red or similar, to emphasise the fact it's what users are going to look for when they open Desura.

**Comment by ssokolow** [comment]
Red is an inappropriate color, both because of how we perceive it (as an agitating alert color) and because of how it clashes with the default theme's color scheme.

However, I have nothing against the idea of a more prominent Play/Games button in general. It's probably partly because Community, Development, and Support do seem a bit overly prominent given how little users like me use them compared to Play/Games and Games/Store. (Something that may be remedied for Community once the friends system is further developed)

Another option for making Play/Games more prominent would just be to make the client start with that as the default active tab.

**Comment by mathrick** [comment]
On Apr 4, 2012 7:19 AM, "Stephan Sokolow" <
reply@reply.github.com>
wrote:

> Red is an inappropriate color, both because of how we perceive it (as an
> agitating alert color) and because of how it clashes with the default
> theme's color scheme.

Red doesn't necessarily mean #FF0000, I meant more of a shade to give it
extra visual impact. But obviously the whole thing needs proper design; I
think the default theme would benefit from some liberally applied
brainstorming. Btw, where do you even get other themes?

**Comment by ssokolow** [comment]
True, but I generally think of reds dark enough to not evoke an alert response as maroons and it's still adding a whole new color to the color scheme.

As for theming, it hasn't really gotten off the ground yet, but there are two alternate themes in the [Desura Tweaks](http://www.desura.com/groups/desura-tweaks/downloads) group. (Those aren't indicative of what you _can_ do. From what I've seen in the code base, Desura's theming system is similar to Firefox's in that you're basically overriding the templates which define the UI.)

**Comment by LiamDawe** [comment]
I think Games and Store much more accurately represents it please change it.

**Comment by Jookia** [comment]
Fixed.

**Comment by ssokolow** [comment]
I'm not sure this can be considered fixed. Yes, it's better, but I"m not sure "Play" and "Store" is better than "Games" and "Store".

More discussion may be necessary.

**Comment by Jookia** [comment]
It's fixed enough because my muscle memory idleness now clicks 'play' instead of 'games'.

**Comment by ssokolow** [comment]
I suppose. I am a bit of a perfectionist.

**Comment by Jookia** [comment]
I don't want to mess up the code <-> display relationships. The buttons usually correspond to internal stuff like playList or gameList.

**Comment by ssokolow** [comment]
Ahh. Fair enough. Keeping terminology consistent is always a good idea.
