### ISSUE TITLE
desurium: add webm support

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#136]
Since the latest version of Flash is the last version for Linux, it's only fitting that we dump that plugin. Who's with me?

EDIT by karolherbst:
We should make desurium stable whily playin webm videos, then desura could replace their flash videos with webm

**Comment by ssokolow** [comment]
I agree, but really?

Just great. The latest version of Flash introduces a bug in the "Use GPU acceleration" feature which swaps the red and blue color channels on, at least, nVidia GPUs.

**Comment by hero1900** [comment]
i am with you too lets dump it

**Comment by karolherbst** [comment]
let us use modern and better technologies :) so I agree, too.

**Comment by lodle** [comment]
When CEF is stable with htlm 5 video im all for this

**Comment by Jookia** [comment]
I neglected mentioning that CEF didn't support it as it's more of a design concept right now, not an actual implementation detail.

How would the site admins do this? IE9 doesn't support webm.

**Comment by lodle** [comment]
There is code all ready on Moddb/desura to do this. Just CEF needs to support it with out crashing first

**Comment by karolherbst** [comment]
so that means, we have to use newer versions of CEF.

Are there any API changes in the patched CEF or just implementation?

**Comment by Protektor-Desura** [comment]
WebM is actually now supported by IE. http://blog.webmproject.org/2011/03/introducing-webm-in-internet-explorer-9.html
That is from over a year ago. You could initially get it as a plug in but now it is part of IE9 by default I believe. It's suppose to be part of the Microsoft Foundation stuff or you can go the route of the Google plugin.

I thought the issue was that none of the videos are encoded as WebM on the Desura server. If that is the case then every video on the system would have to be re-encoded to WebM which is a huge job.  That's assuming all the videos are h.264/aac in a FLV container.

My understanding is the Linux will still get Flash updates but only for Chrome in the future. I am all for pushing towards HTML5 but that seems like it would be a huge project on the server side. HTML5 standard supports WebM and h.264/aac in a MP4 container I believe. My understanding was that Firefox would not support that because of licensing issues. Now Mozilla has said Firefox will call the system utilities/codecs to play h.264/MP4 encoded video as part of the HTML5 specs. WebM should be better supported by browsers than h.264 because of patent issues. The difference in quality and size of video is not enough difference that picking one over the other would really ultimately matter. Most websites are already doing h.264/aac but in a FLV container. So for most of them switching over the MP4 would not require a re-encode but just a move to a new container.

**Comment by Jookia** [comment]
YouTube has all its videos encoded in WebM for HTML5 IIRC. I'd push for WebM in terms of freedom and an open web, but at this point I'm just happy if it runs without Flash.

**Comment by Aloz1** [comment]
I've written a small piece of JS that can detect which browser you are using and make the right changes to the page. I used it to make sure the correct CSS was used with the correct web browser, but it could easily be modified for flash and the html5 video tag. It could be used to make sure that old browsers were still supported (through flash), and then use MP4 with both IE9 and safari (they don't support webm AFAIK). Then everything else can use webm.

EDIT:
Here is a nice link that says which browsers support what video formats: http://www.w3schools.com/html5/html5_video.asp

**Comment by karolherbst** [comment]
since we are not allowed to distribute CEF with the ability to show h.264 based videos we have to use webm. All chromium builds are shiped without h.264 support as well.

Because chromiums supports webm since version 6 and the desura cef is based on chromium 14 desura should already support this by default.

**Comment by Jookia** [comment]
Not that that's surprising, but could you source that? If it's over patent concerns, then I'd say to just ignore it.

**Comment by karolherbst** [comment]
we can only ignore them, if desura is built by user. Using is not the problem, distributing is

**Comment by lodle** [comment]
I looked at using webm but cef kept crashing on the demos. Might be worth retrying as i can upgrade the backend to support webm if needed.

**Comment by Protektor-Desura** [comment]
We are going to have to switch to something besides Flash support on Linux. There are not going to be anymore Flash plug-ins available on Linux. Google is taking over Flash support/development on Linux and embedding it in Chrome and who knows how long that will actually last since they own WebM. Flash will not be offered in Chromium. Our only option is to support HTML5 videos (WebM) in the client going forward. We can't directly support MP4 since there are patent issues when it comes to redistribution and none of the Linux distros would touch the client with MP4 built in. I think the only option is to support WebM in the client.

**Comment by lodle** [comment]
Karolherbst: http://www.wellesley.edu/~kenny/html5/vp8.html (webm test)

**Comment by karolherbst** [comment]
I get the following error message:

[0515/101705:INFO:gl_implementation.cc(100)] Using desktop GL implementation.

**Comment by Jookia** [comment]
Okay, I've just uninstalled Flash because it's gotten to the point that Gnash works worse, but it's more stable. If it can't play a video, it won't take Desura with it.

**Comment by karolherbst** [comment]
moved into 0.9 milestone: we should make desurium stable with webm usage. Dropping flash is done by desura itself then (maybe)

**Comment by karolherbst** [comment]
I think we should try to build CEF with system vpx, maybe this will allow us to view webm video files

**Comment by karolherbst** [comment]
This should not break, because libvpx is API compatible since 0.9.6 (required by chromium 14)

**Comment by karolherbst** [comment]
I think we have just to install libffmpegsumo.so from the CEF build, I will try this out
