### ISSUE TITLE
Unable to play video (linux)

### ISSUE THREAD

**Issue by Aloz1** [desura/Desurium#173]
Under the Linux client (build 120.21) on Linux mint 12, I am unable to properly play videos. I click the play button, everything goes dark, then the audio starts playing with no video. Another interesting thing to note is that even though the background has dulled, I am able to scroll up and down still (not sure if it's supposed to do that, just thought I might plop it in there as well). Is there anything I can do to help test what may be happening?

**Comment by ssokolow** [comment]
120.21 is the official release and predates the GPLing of the code. The problem you describe is a known issue that I and various other people can confirm.

Unless there's been a regression since I last tried the development builds, it's already fixed in the GPLed codebase and the fix will be in the first community release.

**Comment by Aloz1** [comment]
Thanks, I'll get myself a copy of the codebase then :)
