### ISSUE TITLE
ubuntu 12.04 install deps issue

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#201]
On 12.04 install deps can't find these;

No packages found matching libevent-dev.
No packages found matching libflac-dev.
No packages found matching libjpeg62-dev.
No packages found matching libspeex-dev.
No packages found matching libsqlite3-dev.
No packages found matching libtinyxml-dev.
No packages found matching libwebp-dev.
No packages found matching libxml2-dev.
No packages found matching libxslt1-dev.
No packages found matching yasm.

**Comment by karolherbst** [comment]
yeah, but apt-get ask to install them, doesn't it?

**Comment by ssokolow** [comment]
That's really the crux of the matter. On 11.10, `install-deps.sh` shows similar output, but then calls `apt-get` to install them.

It would probably be better to use something like `2>/dev/null` to silence those warnings though, since they can definitely be mistaken for problems rather than side-effects of normal operation.
