### ISSUE TITLE
Styling Issue - Scrollbar colours

### ISSUE THREAD

**Issue by LiamDawe** [desura/Desurium#239]
This should be a trivial bug fix, make the scrollbars the same colour on all sections, looks odd on the play section to have a black scrollbar than all other tabs grey?

Just a styling issue.

**Comment by Jookia** [comment]
This may be an issue with CEF.

**Comment by karolherbst** [comment]
yes, the scrollbars are the same I see in chromium.

**Comment by Smilex** [comment]
Perhaps it's done using this -> http://www.webkit.org/blog/363/styling-scrollbars/
In which case fixing this bug would involve access to the page's web files. Also Cheeseness did mention something about Play not being a web page, which would explain the difference.
How to fix this issue? One way would be to replicate the style of the scrollbar from Play, into CSS code and link them to the other pages. I don't know if you can change the scrollbar internally.

**Comment by Smilex** [comment]
it seems that the Store page does try to link to scrollbar.css by using the format desura://theme/css/scrollbar.css
Solving this issue will involve figuring out how that format works, and if desura:// is supposed to point to the executable, desuraNET will need to change the path, because scrollbar.css is currently located at Desurium/install/themes/default/css/scrollbar.css

**Comment by karolherbst** [comment]
mhh once I found the part with the "desura://" handling. And I am a bit aware of the installation of theme files and stuff, I will take care of this bug.

**Comment by karolherbst** [comment]
regression with some build options

**Comment by karolherbst** [comment]
this happens, because there are "/.." in the path.

**Comment by karolherbst** [comment]
it converts .. in .
