### ISSUE TITLE
add posibility to build CEF and desura separately

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#258]
this would be great, because it would be possible to install CEF without desura system wide, which will help devs a lot (decreasing build time).
Further it would be better to have 2 ebuilds (one for CEF and one for desura only)

**Comment by TheSiege** [comment]
there was an option to disable the cef build; a first approach could be to make a seperate option to disable desurium build; then hunt stuff down that desura needs in term of cef and then go on from that

**Comment by censlin** [comment]
I'd like to suggest a move to Webkit-gtk. I don’t have much to back up this suggestion though, since I don’t really know much about either Chrome or Webkit. It might get rid of a lot of Chrome specific things (Webkit source 5 MiB, Chromium source 100+ MiB). There might also be some minor performance improvements (I find Midori to be slightly faster than Chromium), but I wouldn’t bet money on it though. Also, Webkit already has a gtk3 port, so it might make that future upgrade a little easier.

**Comment by karolherbst** [comment]
webkit-gtk is very low level and not a browser, so because we need plugin support (currently for flash videos), we have to implement nsplugin support ourself with a move to webkig-gtk.

Further chromium is using plain webkit, so I don't think so, that a move to webkit-gtk will make much sense at the moment

**Comment by censlin** [comment]
Fair enough

**Comment by ssokolow** [comment]
I'm also not sure how well webkit-gtk would work in a wxWidgets application, given that it doesn't use GTK+ if compiled for Windows or MacOS.

**Comment by censlin** [comment]
Valid point. It seems that wxWidgets has a wxWebView component that binds to webkit on OSX/GTK+ or MSW on Windows. So, using Webkit directly would be a bad idea.

**Comment by Mailaender** [comment]
If you want the latest flash player for Linux you have to stick to Chromium and it's pepper API. http://blogs.adobe.com/flashplayer/2012/02/adobe-and-google-partnering-for-flash-player-on-linux.html

But actually I am just commenting this to get updates on the issue because this would ease creating RPMs.

**Comment by ssokolow** [comment]
@Mailaender Actually, as far as I know, you have to actually use official Chrome because Chromium doesn't include the Pepper Flash plugin.

As for getting updates, next time, just choose "Watch" from the drop down button below the comment box.
