### ISSUE TITLE
Question about choice of Chromium

### ISSUE THREAD

**Issue by posophe** [desura/Desurium#271]
Hello,

I have seen a time ago a discussion about usage of webkitgtk and a major fact i pick up is usage of Flash. But why don't used HTML5  <video> instead of flash animations or xulrunner ?

Best regards.
Benjamin Denisart

**Comment by ssokolow** [comment]
This is an issue tracker, not a question-answer system. You really should have used the search box. Even if you didn't find issue #136 (Replace Flash with HTML5), you could have asked in issue #258 (where WebKitGTK was mentioned) rather than opening a whole new issue.

To answer your question: They want to switch to HTML5 `<video>` tags, but it's not as simple as it sounds. They have to get it working without bugs on the client side and then adjust the servers to offer the videos in WebM format. Both are time-consuming tasks.
