### ISSUE TITLE
master and 0.8.0_rc10 have wrong download links from github

### ISSUE THREAD

**Issue by higuita** [desura/Desurium#595]
I tried to compile desurium and failled. the build script is failling to download some files from github, example:
https://github.com/downloads/lodle/Desurium/depot_tools-145556-2.tar.gz

Here is the log: http://pastebin.com/gK0q2RMZ

that file (and others) are giving 404

in IRC Anagromataf point me to a new location:

https://sourceforge.net/projects/desurium/files/depot_tools-145556-2.tar.gz

Editing the CMakeLists.txt to the new locations fixes the problem

thanks

**Comment by karolherbst** [comment]
the problem here will be, that cmake remembers the old location, because you are allowed to set custom download locations. Sadly there is nothing we can do about.

This issue was fixed anyway here:
master: https://github.com/desura/Desurium/commit/93eaf6ebea120589e5f63afda17bd58b0e72d8c6
0.8: https://github.com/desura/Desurium/commit/df9c339bcd569daf32f5bad4c837e6af9ff6e5d9

This issue won't occur with a "clean" project configurations, which is used by automatic build tools anyway (for package manager, new downloads of the desurium code base, clean uip, ...).

I am sorry, but it would make things worse if we try to add "checks" to find out if the old values are used.
