### ISSUE TITLE
No Desurium Branding

### ISSUE THREAD

**Issue by Jookia** [desura/Desurium#72]
Currently the Desurium branding is broken (as in, nothing, and it included the Desura logo)

This needs to be fixed for copyright reasons for the next release.

**Comment by lopho** [comment]
https://github.com/lodle/Desurium/issues/55

**Comment by Jookia** [comment]
I've done this: http://opengameart.org/forumtopic/desurium-art-request-foss-desura

**Comment by etinquis** [comment]
I tossed a couple concepts together: http://i.imgur.com/YnBjB.png.  Made in inkscape, so I've got the svg if you like it.

**Comment by etinquis** [comment]
@Jookia Any feedback?  Totally off the mark?  Were you just looking for a recolor a la chromium?

**Comment by Jookia** [comment]
Oh sorry, I forgot to reply. It looks a little too similiar to the official Desura logo.

**Comment by etinquis** [comment]
Okay, my apologies, I assumed it should be similar.  Do you have any ideas for theme or subject matter if it is to be different?

**Comment by Jookia** [comment]
Maybe a silhoutte with a gear in front? I don't know.

**Comment by notshi** [comment]
hey guys, saw jookia's post in opengameart, made an account here to post something i came up with just now. you can use it if you want or not, up to you.

http://esyou.com/data/desu

thought a mascot would be fun with the top bit (his hat?) being customisable for future uses (idea bulb, game cog, pixel loot, any other game related icons). i made it blue for you so the css bit wouldn't be a nightmare but obviously, desubot (heh) can be coloured in a myriad of ways. anyways, good luck with the project and message me if you need the source file (svg inkscape) or anything else.

cheers.

**Comment by Jookia** [comment]
Desubot seems to be awesome! A mascot would really be nice. One thing I just thought about would be to have instead of the text, a silhouette badge of the Desura rock. I like the last one a lot. One thing cool would to have the second eye as a gear of some kind, which may emphasize 'look, it's a robot' a bit more. The objects above the head seems a little.. Odd. Seeing as it's separate from the mascot.

**Comment by notshi** [comment]
something more like this - http://esyou.com/data/desubot/ ?

**Comment by Jookia** [comment]
Something _exactly_ like that. I'd have to get the other's input on this, but you have my vote. And anybody else's vote I can steal.

**Comment by notshi** [comment]
excellent :} 

i've put all the files here if you need them - https://github.com/notshi/desubot

**Comment by Jookia** [comment]
Thanks! What license is it under?

**Comment by notshi** [comment]
public domain. i should probably type that in to the repo somewhere!

**Comment by Jookia** [comment]
Technically public domain is a bad choice, as some countries don't allow it. Maybe CC0?

**Comment by notshi** [comment]
i'll add that in then!

**Comment by Protektor-Desura** [comment]
Let me say something here. You are allowed to use the Desura branding under the rules posted on the Branding page. What you can't do is alter the official source and still use the Desura branding. If you alter the source from the official release version then you have to name it something else and use some other graphics. Basically the same type of rules as Firefox.

If your wanting a whole new mascot/icon, then I love the robot one and I think both eyes not just one should be a gear. If your not going to make both eyes gears then maybe put the gear where the logo outline is right now and make the eyes just circles. I would have to ask about the outline of the logo, if they have a problem with it. I assume it would eventually be made into a SVG so it could be resized to any size. Who knows, Scott might even want to make it an official mascot for Desura. Of course it would still be CC0 or whatever you guys decide.

The Desura client is suppose to be based on the Desurium source code. The difference is that the official Desura client probably isn't going to update/released as fast as the open source version might be. Basically the official client is going to have to be the stable releases and not all the versions in between. 

The official client is still going to download all the non-standard libraries rather than depend on a package manager. We need it to just work across as many different Linux distributions as possible.  I personally don't want to see users have to pick anything. Right now they don't, the system looks at what your web browser reports to the server and then offers you the correct one based on that information. Users basically don't have to pick what they want just download and install. 

I would really like to see the first download version for Linux remove the tar.ball and just have the one file inside the tarball to download. i would like to see it default to installing in ~/Desura. You can still move it to whatever you want. I just think it should be a click on it and it just works. The less the user has to pick and the more Linux systems it works on the better I think it is.

**Comment by Jookia** [comment]
Whoa man, getting a little bit off topic. Maybe that should be put in a FAQ? Installing it in ~/Desura is possible with the current system. If Desura wants to bundle it's libraries, that's up to it. No changes are needed.

Also, Desurium can be run in ~/Desura, but it will still write to ~/.config/desura, which is why I've kind of thought of just having Desurium be a program, and storing config and downloaded games in the user's ~/.local/share/desura folder.

**Comment by notshi** [comment]
did a few revisions based on your request. anyone is free to jump in and move bits around if they want to, the source being the similar named .svg file found in the same repo.

https://github.com/notshi/desubot/blob/master/desurium002.png

**Comment by Jookia** [comment]
I love the bottom left one.

**Comment by notshi** [comment]
personally i liked the first one you requested with the non-symmetrical eyes ~ it added some character to the bot.

**Comment by LiamDawe** [comment]
Bottom left one for me too, looks fun.

**Comment by Jookia** [comment]
Ah, character. I don't know then.

**Comment by Protektor-Desura** [comment]
Bottom left is what I like and then I would say bottom middle or top left for my second choices.

**Comment by Cheeseness** [comment]
I've just submitted a pull request with updated branding images.
I also modified the desubot design to be symmetrical and have committed an Inkscape SVG with the defferent chest symbols and eye variants as layers that can easily be shown and hidden for anybody who wants to do future work with it.

**Comment by Protektor-Desura** [comment]
I am just curious if anyone read the branding Wiki page that was put up about how you can use the Desura logos and such.
https://github.com/lodle/Desurium/wiki/Branding

I would think that it would make a lot of this beside the point, unless you just want a mascot.

**Comment by Cheeseness** [comment]
I believe I had read it previously, but perhaps not. Either way, I suspect that one of the main motivations is/was to have something that is not owned by or referencing a specific entity beyond the Desurium community project (allowing it to have a distinct identity), would allow community derivatives, and also me compatible with the policies of distribution projects like Debian which require freedoms beyond the restrictions laid out in those usage guidelines (if you're not aware, Debian carries (if you're not aware, Debian's repos carry the unbranded fork Iceweasel instead of Firefox for just this reason).

**Comment by Protektor-Desura** [comment]
I was not aware of that since I don't use Debian. All the distros I have played with/used have had Firefox installed.

**Comment by Cheeseness** [comment]
I think there are a bunch of others that ship with Iceweasel as well. At any rate, it's nice to have something that the community can use/modify without fear of impinging on trademarks :)

**Comment by LiamDawe** [comment]
Probably best to have the new branding for the mentioned issues, never a problem getting it included anywhere then :)

**Comment by Jookia** [comment]
Woop.
